[package]
name = "lt-world"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
typst.workspace = true
typst-kit.workspace = true

chrono.workspace = true
dirs.workspace = true
